classify: classify.cpp
	g++ -o classify.out classify.cpp
	./classify.out

regression: regression.cpp
	g++ -o regression.out regression.cpp
	./regression.out

test: test.cpp
	g++ -o test.out test.cpp
	./test.out

